export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const PRODUCT_OPTION_REPOSITORY = 'PRODUCT_OPTION_REPOSITORY';
export const PRODUCT_OPTION_VALUE_REPOSITORY =
  'PRODUCT_OPTION_VALUE_REPOSITORY';
export const PRODUCT_SKU_REPOSITORY = 'PRODUCT_SKU_REPOSITORY';
export const PRODUCT_SKU_VALUE_REPOSITORY = 'PRODUCT_SKU_VALUE_REPOSITORY';
